# Branch iOS SDK - SwiftLint Configuration
# Strict concurrency and modern Swift 6 rules

# Paths
included:
  - Sources
  - Tests
  - Examples

excluded:
  - .build
  - .tuist-bin
  - Tuist/Dependencies
  - DerivedData
  - Package.swift

# Enabled Rules
opt_in_rules:
  # Code Quality
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_deinit
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled Rules
disabled_rules:
  - todo # We use expiring_todo instead
  - trailing_whitespace # SwiftFormat handles this

# Rule Configurations
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration

# Line Length
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true

# Type Body Length
type_body_length:
  warning: 250
  error: 350

# File Length
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

# Function Body Length
function_body_length:
  warning: 40
  error: 60

# Function Parameter Count
function_parameter_count:
  warning: 5
  error: 8

# Cyclomatic Complexity
cyclomatic_complexity:
  warning: 10
  error: 15

# Type Name
type_name:
  min_length: 3
  max_length: 50
  validates_start_with_lowercase: error

# Identifier Name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ok
    - to
    - up
    - i
    - x
    - y
    - z

# Nesting
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 4

# File Header
file_header:
  required_pattern: |
    \/\/ .*\.swift
    \/\/ Branch iOS SDK.*
    \/\/
    \/\/ Copyright © \d{4} Branch Metrics\. All rights reserved\.
    \/\/ SPDX-License-Identifier: MIT

# Closure Body Length
closure_body_length:
  warning: 30
  error: 50

# Collection Alignment
collection_alignment:
  align_colons: true

# Modifier Order (Swift 6 compatible)
modifier_order:
  preferred_modifier_order:
    - override
    - acl
    - setterACL
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned

# Missing Docs
missing_docs:
  excludes_extensions: true
  excludes_inherited_types: false
  warning:
    - open
    - public

# Expiring Todo - format: // TODO: [01/01/2025] description
expiring_todo:
  approaching_expiry_severity: warning
  expired_severity: error

# Force Unwrapping
force_unwrapping:
  severity: error

# Implicit Return
implicit_return:
  included:
    - closure
    - getter

# Number Separator
number_separator:
  minimum_length: 5

# Sorted Imports
sorted_imports:
  severity: warning

# Trailing Closure
trailing_closure:
  only_single_muted_parameter: true

# Type Contents Order
type_contents_order:
  order:
    - associated_type
    - type_alias
    - case
    - subtype
    - type_property
    - instance_property
    - ib_inspectable
    - ib_outlet
    - initializer
    - deinitializer
    - type_method
    - view_life_cycle_method
    - ib_action
    - other_method
    - subscript

# Reporter
reporter: "xcode"
