target 'tvOSReleaseTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Branch'

end

target 'tvOSReleaseTestTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Branch'

end
