desc "Add Branch keys and Universal Link domains to BranchPluginExample"
lane :update do
  # This app is not currently set up properly for test in the Dashboard. Use the :force for now.
  setup_branch live_key: "key_live_feebgAAhbH9Tv85H5wLQhpdaefiZv5Dv",
               test_key: "key_test_hdcBLUy1xZ1JD0tKg7qrLcgirFmPPVJc",
     app_link_subdomain: "bnctestbed",
              xcodeproj: "WebViewExample.xcodeproj",
                  force: true
end

desc "Add Branch keys and Universal Link domains to BranchPluginExample and commit to Git"
lane :update_and_commit do
  setup_branch live_key: "key_live_feebgAAhbH9Tv85H5wLQhpdaefiZv5Dv",
     app_link_subdomain: "bnctestbed",
              xcodeproj: "WebViewExample.xcodeproj",
                 commit: true, # Use a string here for a custom commit message
                  force: true
end

desc "Validate Universal Link settings for a project"
lane :validate do
  # The :domains parameter is optional.
  # Without it, validation passes if at least one domain exists in the project and
  # all domains pass validation.
  # With this parameter, the applinks: domains in the project must match this list.
  # Order is irrelevant.
  # This app is not currently set up properly for test in the Dashboard. Validation
  # will currently fail for those domains.
  validate_universal_links domains: %w{
    bnctestbed.app.link
    bnctestbed-alternate.app.link
    bnctestbed.test-app.link
    bnctestbed-alternate.test-app.link
  }
end
