platform :ios, '9.0'

target "TestBed-Swift" do
  pod 'Adjust', '~> 4.11.4'
  pod 'Mixpanel'
  pod 'Amplitude-iOS', '~> 3.14.1'
  pod 'AppsFlyerFramework'
  pod 'Tune'
  pod 'GoogleAnalytics'
  pod 'Appboy-iOS-SDK'
  pod 'YandexMobileMetrica/Dynamic', '2.9.1'
  pod 'Localytics', '~> 4.4'
  pod 'mParticle-Apple-SDK', '~> 6'
end
