require_relative 'lib/helper/update_helper'

fastlane_version "2.69.0"

lane :prepare_pods do
  # This helps optimize CI with caching by testing whether a pod install is necessary
  pod_install_if_required '../Branch-TestBed', verbose: true
end
