use_frameworks!
platform :ios, '9.0'

# ----- Branch pod
#
# Take the Branch pod from this repo rather than CocoaPods.
# Don't use the path: argument if you want the production
# release from CocoaPods., e.g.:
#
# pod "Branch"

# ----- Application target

target 'WebViewExample' do
  project 'WebViewExample'
  pod 'Branch', path: "../.."
  pod 'Cartography', '3.0.1'
  pod 'MBProgressHUD'
end

# Add custom configurations. This informs CocoaPods that Test-Debug should be treated like
# a debug build, not a release build, when building pods. In particular this means the
# Branch SDK will be built with the DEBUG flag when using this configuration.
# https://github.com/BranchMetrics/react-native-branch-deep-linking/blob/master/docs/branch-environments.md#step-7-update-podfile
project "WebViewExample", "Test-Debug" => :debug
