#!/bin/bash
set -euo pipefail

# deploy-release  -  The release deployment master script.
#
# This script is written to be excessively modular so it can be debugged or restarted easily.
#
# Edward Smith, December 2016

scriptfile="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scriptfile="${scriptfile}"/$(basename "$0")
cd $(dirname "$scriptfile")/..

scriptFailed=1
function finish {
    if [ $scriptFailed -ne 0 ]; then
        echo ">>> Error: `basename "$scriptfile"` failed!" 1>&2
        exit 1
    fi
}
trap finish EXIT


version=$(./scripts/version)

echo ""
echo "Before continuing:"
echo "- Make sure that the release version number is already updated."
echo "- Make sure that the ChangeLog.md has been updated, spell checked, and is coherent."
echo "- Make sure that you are logged in to your Branch Google account and have write access to Google Groups."
echo ""
if ! ./scripts/askYN "Deploy Branch release version ${version}?"; then
    echo ">>> Nothing deployed." 1>&2
    exit 1
fi

# Check that deployment software is installed
./scripts/deploy-preflight

# Prompt for editor input for ChangeLog.
vim +4 +star ChangeLog.md

# Pre-release CocoaPod lint
echo ">>> Linting build for release..." 1>&2
pod lib lint Branch.podspec --verbose

# Build the framework
echo ">>> Building the framework..." 1>&2
./scripts/deploy-build-framework

# Make the zip files and get the checksums
echo ">>> Zipping and checksumming framework files..." 1>&2
./scripts/deploy-checksum

echo '>>> Making Carthage build...' 1>&2
./scripts/deploy-carthage

echo '>>> The Branch SDK build is successful so far.' 1>&2
if ! ./scripts/askYN "Commit and deploy Branch release version ${version}?"; then
    echo ">>> Nothing deployed." 1>&2
    exit 1
fi

echo '>>> Deploying Fabric build...' 1>&2
./scripts/deploy-fabric

echo '>>> Commit and tag...' 1>&2
./scripts/deploy-git-tag

echo '>>> Pushing Branch CocoaPod...' 1>&2
pod trunk push Branch.podspec

echo '>>> Uploading to AWS...' 1>&2
./scripts/deploy-aws

# Prompts for SDK Release announcements
./scripts/deploy-announce

# Remove remnants:
./scripts/deploy-cleanup

echo ""
echo "The Branch SDK has been released.  Rejoice and pay tribute to Steve Jobs!"
# Completed OK:
scriptFailed=0
