#!/bin/bash
set -euo pipefail

# deploy-build-framework
#
# Edward Smith, August 2017

scriptname=$(basename "${BASH_SOURCE[0]}")
scriptpath="${BASH_SOURCE[0]}"
scriptpath=$(cd "$(dirname "${scriptpath}")" && pwd)
cd ${scriptpath}/../carthage-files

# Build
xcodebuild -scheme 'Branch-xcframework'
