#!/bin/bash
set -euo pipefail

# deploy-carthage  --  Deploy the Branch.framework with Carthage
#
# Edward Smith, November 2016

scriptname=$(basename "${BASH_SOURCE[0]}")
scriptpath="${BASH_SOURCE[0]}"
scriptpath=$(cd "$(dirname "${scriptpath}")" && pwd)
cd ${scriptpath}/../carthage-files

scriptFailed=1
function finish {
    if [ $scriptFailed -ne 0 ]; then
        echo ">>> Error: $scriptname failed!" 1>&2
        exit 1
    fi
}
trap finish EXIT

echo ">>> Building 'Branch iOS SDK Carthage'."
xcodebuild -scheme 'Branch iOS SDK Carthage' clean build -quiet
carthage build --no-skip-current && carthage archive Branch
scriptFailed=0
