#!/bin/bash

xcrun simctl list devices available >> simulator_list
cat simulator_list | while read LINE; do
   if echo "$LINE" | grep -q "iPhone 1"
   then
        iphoneSimName=$(echo $LINE | awk '{$NF="";sub(/[ \t]+$/,"")}1')
        iphoneSimName=$(echo $iphoneSimName | awk  '{$NF="";sub(/[ \t]+$/,"")}1')
        rm iphoneSim
        echo $iphoneSimName>>iphoneSim
   fi
   if echo "$LINE" | grep -q "Apple TV"
   then
        appleTVSimName=$(echo $LINE | awk '{$NF="";sub(/[ \t]+$/,"")}1')
        appleTVSimName=$(echo $appleTVSimName | awk  '{$NF="";sub(/[ \t]+$/,"")}1')
        rm appleTVSim
        echo $appleTVSimName>>appleTVSim
   fi
done

rm simulator_list
