#!/bin/bash
set -euo pipefail

# pod-update-all  -  Update all CocoaPods before running tests.
#
# Edward Smith, February 2017

scriptfile="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scriptfile="${scriptfile}"/$(basename "$0")
cd $(dirname "$scriptfile")/..

function updatePodsInDirectory() {
    local prevDir=$(pwd)
    local projDir="$1"

    cd "$projDir"
    echo ""
    echo ">>> Updating `pwd`."
    pod install
    pod update
    cd "$prevDir"
}

updatePodsInDirectory Branch-TestBed
updatePodsInDirectory Branch-TestBed-Xcode-7
updatePodsInDirectory Examples/WebViewExample
