#!/bin/bash
set -euo pipefail

# pod-update-all  -  Update all CocoaPods before running tests.
#
# Edward Smith, February 2017

scriptfile="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scriptfile="${scriptfile}"/$(basename "$0")
cd $(dirname "$scriptfile")/..

function updatePodsInDirectory() {
    local prevDir=$(pwd)
    local projDir="$1"
    shift
    local options="$@"
    #echo $options

    cd "$projDir"
    echo ""
    echo ">>> Updating `pwd`."
    if [[ $options = *bundler* ]]
    then
        echo ">>> Executing 'bundle install'..."
        bundle install
    fi
    pod install
    pod update
    cd "$prevDir"
}

gem install cocoapods
gem install bundler
updatePodsInDirectory Branch-TestBed-Swift
updatePodsInDirectory Examples/WebViewExample  bundler
