#!/bin/bash
#  version  -  Version number managment.
#  Edward Smith,  December 2016.
set -euo pipefail
function usage() {
cat <<USAGE
version  -  Print or increment a version number.

Usage:  version  [ -hiMmp ]

With no options given, \`version\` simply prints the current version number.

Version numbers are:  Major.Minor.Patch

Options:

  -h  Print this usage info.
  -i  Increment the version number.  By default increments the patch number.
  -M  Print or increment the \`major\` version number.
  -m  Print or increment the \`minor\` version number.
  -p  Print or increment the \`patch\` version number.

USAGE
}

version=2.0.1

if (( $# == 0 )); then
    echo $version
    exit 0
fi

scriptfile="$( cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
scriptfile="${scriptfile}"/$(basename "$0")
IFS=$'.' read  M m p < <(echo "$version")

major=
minor=
patch=
increment=

while getopts ":hiMmpv" option; do
    case "$option" in
    h)  usage; exit 0 ;;
    i)  increment=true ;;
    M)  major=true ;;
    m)  minor=true ;;
    p)  patch=true ;;
    v)  ;;
    ?)  echo ">>> Error: Unknown option '-$OPTARG'." 1>&2; exit 1 ;;
    esac
done


if [[ $increment ]]; then

    if [[ $major ]]; then
        let M=M+1
        m=0
        p=0
    elif [[ $minor ]]; then
        let m=m+1
        p=0
    else
        let p=p+1
    fi

    version="$M.$m.$p"
    echo "$version"
    sed -i '' -e "s/^version=.*$/version=$version/" "$scriptfile"; exit 0

else

    #  Print the version or parts

    if   [[ $major ]]; then
        echo $M
    elif [[ $minor ]]; then
        echo $m
    elif [[ $patch ]]; then
        echo $p
    else
        echo "$version"
    fi

fi

