#!/bin/bash
set -euo pipefail

# xcode-analyze-infer - Runs the Infer code analyzer on an Xcode project.
#
# Run from the root directory of the project.
#
# Installation
# ------------
# brew install infer
# gem install xcpretty

function clean_up() {
    set +e
    (
        rm compile_commands.json
        rm -Rf infer-out/
        rm xcodebuild.log
    ) &> /dev/null
}
trap clean_up EXIT

xcode_options=""
if (( $# == 1))
then
    xcode_options="-project "$1""
fi

xcodebuild $xcode_options | tee xcodebuild.log
xcpretty -r json-compilation-database -o compile_commands.json < xcodebuild.log > /dev/null
infer run --skip-analysis-in-path Pods --clang-compilation-db-files-escaped compile_commands.json
temp_file=$(mktemp)
cat infer-out/bugs.txt > $temp_file
$EDITOR $temp_file &
