name: Build xcframework with dSyms

on: [push]

jobs:
  build-framework:
    runs-on: macos-14
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: tags/3.6.5
      - name: Build xcframework
        run: |
            ./scripts/prep_xcframework.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_framework
          path: |
            ./Branch.zip
            ./checksum.txt
